before_script:
  - which tox

coverage-clean:
  script: tox -e clean

py27:
  script: tox -v -e py27

py34:
  script: tox -v -e py34

astropy10:
  script: tox -v -e astropy10

numpy110:
  script: tox -v -e numpy110

coverage-report:
  script: tox -e report
