before_script:
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - eval "$(pyenv init -)"
  - pyenv local 3.5.5 3.6.4 3.7.0
  - pip install -U tox tox-pyenv
  - pwd

py35:
  script:
    - tox -v -e py35

py36:
  script:
    - tox -v -e py36

py37:
  script:
    - tox -v -e py37

check-setup:
  script: tox -v -e check

# astropy-dev:
#   allow_failure: true
#   script: tox -v -e astropy-dev

docs:
  script: tox -v -e docs
