before_script:
  - export PATH="$HOME/.local/bin:$PATH"
  - which pip
  - which tox

py35:
  script:
    - tox -v -e py35
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'

astropy13:
  script:
    - tox -v -e astropy13
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'

astropy20:
  script:
    - tox -v -e astropy20
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'

check-setup:
  script: tox -v -e check

# astropy-dev:
#   allow_failure: true
#   script: tox -v -e astropy-dev

docs:
  script: tox -v -e docs
