before_script:
  - which tox

stages:
  - clean
  - test
  - report

coverage-clean:
  stage: clean
  script: tox -e clean

py27:
  stage: test
  script: tox -v -e py27

py34:
  stage: test
  script: tox -v -e py34

astropy10:
  stage: test
  script: tox -v -e astropy10

numpy110:
  stage: test
  script: tox -v -e numpy110

coverage-report:
  stage: report
  script: tox -e report
