before_script:
  - which tox

coverage-clean:
  script: tox -e clean

py27:
  script: tox -v -e py27

py34:
  script: tox -v -e py34

astropy10:
  script: tox -v -e astropy10

astropy11:
  script: tox -v -e astropy11

astropy12:
  script: tox -v -e astropy12

# astropy-dev:
#   allow_failure: true
#   script: tox -v -e astropy-dev

docs:
  script: tox -v -e docs

coverage-report:
  script:
    - tox -e report
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'
