before_script:
  - which tox

coverage-clean:
  script: tox -e clean

py27:
  script: tox -v -e py27

py34:
  script: tox -v -e py34

muselet:
  script: tox -v -e muselet

astropy10:
  script: tox -v -e astropy10

coverage-report:
  script:
    - tox -e report
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'
