before_script:
  - python --version
  - which python
  - which tox

py27:
  script: tox -v -e py27

py34:
  script: tox -v -e py34

astropy10:
  script: tox -v -e astropy10

numpy110:
  script: tox -v -e numpy110
