before_script:
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv local 3.6.3 2.7.14
  - pip install tox
  - pwd

coverage-clean:
  script: tox -e clean

py27:
  script: tox -v -e py27

py36:
  script: tox -v -e py36

astropy13:
  script: tox -v -e astropy13

check-setup:
  script: tox -v -e check

# astropy-dev:
#   allow_failure: true
#   script: tox -v -e astropy-dev

docs:
  script: tox -v -e docs

coverage-report:
  script:
    - tox -e report
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'
